### ISSUE TITLE
Optimisation graphique finale

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/plugin-AlternativeMarketForJeedom#22]
![image](https://user-images.githubusercontent.com/18350629/40367973-ef77e342-5dda-11e8-91b8-23713acd6fe8.png)

- Espacement réduit entre icone et filtres

- Bouton fermer en haut a droite plutôt que sous screenshots

- Filtres autres que Nextdom décochés par défaut

**Comment by Sylvaner** [comment]
Fonctionnement du bouton fermer corrigé

**Comment by Sylvaner** [comment]
Fait
